// Generated by https://quicktype.io

export interface Schedule {
	id?: number;
	weekday: number;
	start_time: number;
	end_time: number;
	workspace_id?: number;
	created_at?: string;
	updated_at?: string;
	deleted_at?: null;
}
