// Generated by https://quicktype.io

import { Schedule } from "./Schedule";
import { User } from "./User";

export interface Workspace {
	id: number;
	name: string;
	slug: string;
	description: null;
	image: null;
	organization_id: number;
	created_at: string;
	updated_at: string;
	deleted_at: null;
	users: User[];
	schedules: Schedule[];
}
